SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%NguyenLieu%'
   OR COLUMN_NAME LIKE '%HanSuDung%'
   OR COLUMN_NAME LIKE '%SoLuongTon%'
ORDER BY TABLE_NAME, COLUMN_NAME;