// <auto-generated />
using System;
using FAB.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FAB.Server.Migrations
{
    [DbContext(typeof(FabDbContext))]
    [Migration("20260701082959_AddNguyenLieuHanSuDung")]
    partial class AddNguyenLieuHanSuDung
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FAB.Server.Models.AiduBaoTonKho", b =>
                {
                    b.Property<int>("MaDuBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDuBao"));

                    b.Property<decimal?>("DoChinhXac")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<string>("MoHinhSuDung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("NgayDuBao")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoLuongDuBao")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("SoLuongThucTe")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaDuBao")
                        .HasName("PK__AIDuBaoT__03C13C223BCA92C8");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("AIDuBaoTonKho", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietDonDatHangNhap", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaDonDatHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(37, 5)")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietD__CDF0A114DAA6EB4C");

                    b.HasIndex("MaDonDatHang");

                    b.HasIndex("MaNguyenLieu");

                    b.ToTable("ChiTietDonDatHangNhap", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(29, 2)")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietD__CDF0A114E14F54AA");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietGioHang");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("HanSuDung")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("HanSuDungDen")
                        .HasColumnType("date");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuNhap")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(37, 5)")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietP__CDF0A11486C59308");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaPhieuNhap");

                    b.ToTable("ChiTietPhieuNhapKho", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietPhieuXuatKho", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaPhieuXuat")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaChiTiet")
                        .HasName("PK__ChiTietP__CDF0A114EB0FBDF5");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaPhieuXuat");

                    b.ToTable("ChiTietPhieuXuatKho", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.ComboChiTiet", b =>
                {
                    b.Property<int>("MaCombo")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPhamCon")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaCombo", "MaSanPhamCon");

                    b.HasIndex("MaSanPhamCon");

                    b.ToTable("ComboChiTiet", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.CongThucSanPham", b =>
                {
                    b.Property<int>("MaCongThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCongThuc"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaCongThuc")
                        .HasName("PK__CongThuc__6E223AF754451582");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CongThucSanPham", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.DanhGiaSanPham", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<byte>("Diem")
                        .HasColumnType("tinyint");

                    b.Property<string>("HoTenKhach")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaSanPham", "MaNguoiDung")
                        .IsUnique()
                        .HasFilter("[MaNguoiDung] IS NOT NULL");

                    b.ToTable("DanhGiaSanPham", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMuc__B3750887EB1EEF4D");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.DonDatHangNhap", b =>
                {
                    b.Property<int>("MaDonDatHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDatHang"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("NgayGiaoHang")
                        .HasColumnType("date");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoDuyet");

                    b.HasKey("MaDonDatHang")
                        .HasName("PK__DonDatHa__17C939D18328AE48");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("DonDatHangNhap", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiDonHang")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("TaiCho");

                    b.Property<int?>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("MaVoucher")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTamTinh")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrackingToken")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoBep");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584ADD986E8AC");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("MaVoucher");

                    b.HasIndex("TrackingToken")
                        .IsUnique()
                        .HasFilter("[TrackingToken] IS NOT NULL");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.GiaoHang", b =>
                {
                    b.Property<int>("MaGiaoHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoHang"));

                    b.Property<string>("DiaChiGiao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int?>("MaShipper")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGiao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiNhan")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PhiGiaoHang")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SdtnguoiNhan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDTNguoiNhan");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoLayHang");

                    b.HasKey("MaGiaoHang")
                        .HasName("PK__GiaoHang__81CCF4FD0498BFBE");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaShipper");

                    b.ToTable("GiaoHang", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaGioHang")
                        .HasName("PK__GioHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.HinhAnhSanPham", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("bit");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnh")
                        .HasName("PK__HinhAnhS__A9C37A9BB1378664");

                    b.HasIndex("MaSanPham");

                    b.ToTable("HinhAnhSanPham", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoHoaDon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChuaThanhToan");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13BBB10A6FB");

                    b.HasIndex(new[] { "SoHoaDon" }, "UQ__HoaDon__012E9E531680A0A5")
                        .IsUnique();

                    b.HasIndex(new[] { "MaDonHang" }, "UQ__HoaDon__129584AC8EE5CE08")
                        .IsUnique();

                    b.ToTable("HoaDon", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhachHang"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("MaKhachHang")
                        .HasName("PK__KhachHan__88D2F0E525763918");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.LichSuChatAi", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("MaPhienChat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDungAi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDungAI");

                    b.Property<string>("NoiDungNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaLichSu")
                        .HasName("PK__LichSuCh__C443222ABC2D70DE");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LichSuChatAI", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.LichSuTonKho", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiThayDoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayGhiNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NguoiThucHien")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuongSau")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("SoLuongThayDoi")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("SoLuongTruoc")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("MaLichSu")
                        .HasName("PK__LichSuTo__C443222AAD287400");

                    b.HasIndex("MaNguyenLieu");

                    b.HasIndex("NguoiThucHien");

                    b.ToTable("LichSuTonKho", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.MaGiamGia", b =>
                {
                    b.Property<int>("MaVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVoucher"));

                    b.Property<int>("DaDung")
                        .HasColumnType("int");

                    b.Property<decimal>("DieuKienToiThieu")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiamToiDa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("GioiHanMotEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiGiam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<int?>("SoLuongToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenVoucher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaVoucher")
                        .HasName("PK__MaGiamGi__0AAC5B11EA9AD036");

                    b.HasIndex(new[] { "MaCode" }, "UQ__MaGiamGi__152C7C5C565E6B72")
                        .IsUnique();

                    b.ToTable("MaGiamGia");
                });

            modelBuilder.Entity("FAB.Server.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D762549B4D72");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D105348E2DD461")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.NguyenLieu", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguyenLieu"));

                    b.Property<string>("DonVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateOnly?>("HanSuDungDen")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("HanSuDungTu")
                        .HasColumnType("date");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("MucTonToiThieu")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("TenNguyenLieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNguyenLieu")
                        .HasName("PK__NguyenLi__C7519355AE1E9493");

                    b.ToTable("NguyenLieu", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.NguyenLieuNcc", b =>
                {
                    b.Property<int>("MaNguyenLieu")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaCungCap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsUuTien")
                        .HasColumnType("bit");

                    b.Property<int?>("ThoiGianGiao")
                        .HasColumnType("int");

                    b.HasKey("MaNguyenLieu", "MaNhaCungCap")
                        .HasName("PK__NguyenLi__826C3A75CDB75CB7");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("NguyenLieu_NCC", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNhaCungCap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhaCungCap"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaNhaCungCap")
                        .HasName("PK__NhaCungC__53DA92050A347E88");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.PhieuNhapKho", b =>
                {
                    b.Property<int>("MaPhieuNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuNhap"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayDenHan")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SoDaTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoXacNhan");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChuaTra");

                    b.HasKey("MaPhieuNhap")
                        .HasName("PK__PhieuNha__1470EF3B2F33770D");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("PhieuNhapKho", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.PhieuXuatKho", b =>
                {
                    b.Property<int>("MaPhieuXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhieuXuat"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LyDoXuat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoXacNhan");

                    b.HasKey("MaPhieuXuat")
                        .HasName("PK__PhieuXua__26C4B5A2339A8E75");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("PhieuXuatKho", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.Quyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__Quyen__1D4B7ED4F0FCF2BD");

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("DonVi")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Ly");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("GiaGoc")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442D3EEBF84C");

                    b.HasIndex("MaDanhMuc");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.SanPhamTopping", b =>
                {
                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<int>("MaTopping")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaThem")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaSanPham", "MaTopping")
                        .HasName("PK__SanPham___F9FB6BEBB370F386");

                    b.HasIndex("MaTopping");

                    b.ToTable("SanPham_Topping", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("ThoiGianThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ChoDuyet");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__ThanhToa__D4B25844F58BED61");

                    b.HasIndex("MaHoaDon");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.TinTuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuc"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AnhPhu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTinTuc");

                    b.ToTable("TinTuc", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.Topping", b =>
                {
                    b.Property<int>("MaTopping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTopping"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TenTopping")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaTopping")
                        .HasName("PK__Topping__33C2FC615D2FC689");

                    b.ToTable("Topping", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("MaVaiTro")
                        .HasName("PK__VaiTro__C24C41CFFDB03D2B");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("VaiTroQuyen", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<int>("MaQuyen")
                        .HasColumnType("int");

                    b.HasKey("MaVaiTro", "MaQuyen")
                        .HasName("PK__VaiTro_Q__9398F6221407973D");

                    b.HasIndex("MaQuyen");

                    b.ToTable("VaiTro_Quyen", (string)null);
                });

            modelBuilder.Entity("FAB.Server.Models.AiduBaoTonKho", b =>
                {
                    b.HasOne("FAB.Server.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("AiduBaoTonKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__AIDuBaoTo__MaNgu__41EDCAC5");

                    b.Navigation("MaNguyenLieuNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietDonDatHangNhap", b =>
                {
                    b.HasOne("FAB.Server.Models.DonDatHangNhap", "MaDonDatHangNavigation")
                        .WithMany("ChiTietDonDatHangNhaps")
                        .HasForeignKey("MaDonDatHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaDon__0C85DE4D");

                    b.HasOne("FAB.Server.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("ChiTietDonDatHangNhaps")
                        .HasForeignKey("MaNguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaNgu__0D7A0286");

                    b.Navigation("MaDonDatHangNavigation");

                    b.Navigation("MaNguyenLieuNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("FAB.Server.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaDon__2739D489");

                    b.HasOne("FAB.Server.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__MaSan__282DF8C2");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("FAB.Server.Models.GioHang", "MaGioHangNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGioHang__MaGioHang");

                    b.HasOne("FAB.Server.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGioHang__MaSanPham");

                    b.Navigation("MaGioHangNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietPhieuNhapKho", b =>
                {
                    b.HasOne("FAB.Server.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("ChiTietPhieuNhapKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaNgu__75A278F5");

                    b.HasOne("FAB.Server.Models.PhieuNhapKho", "MaPhieuNhapNavigation")
                        .WithMany("ChiTietPhieuNhapKhos")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaPhi__74AE54BC");

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("MaPhieuNhapNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.ChiTietPhieuXuatKho", b =>
                {
                    b.HasOne("FAB.Server.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("ChiTietPhieuXuatKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaNgu__7E37BEF6");

                    b.HasOne("FAB.Server.Models.PhieuXuatKho", "MaPhieuXuatNavigation")
                        .WithMany("ChiTietPhieuXuatKhos")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietPh__MaPhi__7D439ABD");

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("MaPhieuXuatNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.ComboChiTiet", b =>
                {
                    b.HasOne("FAB.Server.Models.SanPham", "MaComboNavigation")
                        .WithMany("ComboChiTiets")
                        .HasForeignKey("MaCombo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAB.Server.Models.SanPham", "MaSanPhamConNavigation")
                        .WithMany("ComboThanhPhanCua")
                        .HasForeignKey("MaSanPhamCon")
                        .IsRequired();

                    b.Navigation("MaComboNavigation");

                    b.Navigation("MaSanPhamConNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.CongThucSanPham", b =>
                {
                    b.HasOne("FAB.Server.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("CongThucSanPhams")
                        .HasForeignKey("MaNguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__CongThucS__MaNgu__6754599E");

                    b.HasOne("FAB.Server.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("CongThucSanPhams")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK__CongThucS__MaSan__66603565");

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.DanhGiaSanPham", b =>
                {
                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FAB.Server.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.DonDatHangNhap", b =>
                {
                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiTaoNavigation")
                        .WithMany("DonDatHangNhaps")
                        .HasForeignKey("MaNguoiTao")
                        .IsRequired()
                        .HasConstraintName("FK__DonDatHan__MaNgu__09A971A2");

                    b.HasOne("FAB.Server.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("DonDatHangNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .IsRequired()
                        .HasConstraintName("FK__DonDatHan__MaNha__08B54D69");

                    b.Navigation("MaNguoiTaoNavigation");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.DonHang", b =>
                {
                    b.HasOne("FAB.Server.Models.KhachHang", "MaKhachHangNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhachHang")
                        .HasConstraintName("FK__DonHang__MaKhach__2180FB33");

                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiTaoNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiTao")
                        .HasConstraintName("FK__DonHang__MaNguoi__22751F6C");

                    b.HasOne("FAB.Server.Models.MaGiamGia", "MaVoucherNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaVoucher")
                        .HasConstraintName("FK__DonHang__MaVouch__236943A5");

                    b.Navigation("MaKhachHangNavigation");

                    b.Navigation("MaNguoiTaoNavigation");

                    b.Navigation("MaVoucherNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.GiaoHang", b =>
                {
                    b.HasOne("FAB.Server.Models.DonHang", "MaDonHangNavigation")
                        .WithMany("GiaoHangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK__GiaoHang__MaDonH__3A4CA8FD");

                    b.HasOne("FAB.Server.Models.NguoiDung", "MaShipperNavigation")
                        .WithMany()
                        .HasForeignKey("MaShipper")
                        .HasConstraintName("FK_GiaoHang_Shipper");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaShipperNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.GioHang", b =>
                {
                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("GioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GioHang__MaNguoiDung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.HinhAnhSanPham", b =>
                {
                    b.HasOne("FAB.Server.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("HinhAnhSanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HinhAnhSa__MaSan__5629CD9C");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.HoaDon", b =>
                {
                    b.HasOne("FAB.Server.Models.DonHang", "MaDonHangNavigation")
                        .WithOne("HoaDon")
                        .HasForeignKey("FAB.Server.Models.HoaDon", "MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK__HoaDon__MaDonHan__2FCF1A8A");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.KhachHang", b =>
                {
                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__KhachHang__MaNgu__47DBAE45");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.LichSuChatAi", b =>
                {
                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("LichSuChatAis")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK__LichSuCha__MaNgu__3E1D39E1");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.LichSuTonKho", b =>
                {
                    b.HasOne("FAB.Server.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("LichSuTonKhos")
                        .HasForeignKey("MaNguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__LichSuTon__MaNgu__6B24EA82");

                    b.HasOne("FAB.Server.Models.NguoiDung", "NguoiThucHienNavigation")
                        .WithMany("LichSuTonKhos")
                        .HasForeignKey("NguoiThucHien")
                        .HasConstraintName("FK__LichSuTon__Nguoi__6C190EBB");

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("NguoiThucHienNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.NguoiDung", b =>
                {
                    b.HasOne("FAB.Server.Models.VaiTro", "MaVaiTroNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK__NguoiDung__MaVai__4316F928");

                    b.Navigation("MaVaiTroNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.NguyenLieuNcc", b =>
                {
                    b.HasOne("FAB.Server.Models.NguyenLieu", "MaNguyenLieuNavigation")
                        .WithMany("NguyenLieuNccs")
                        .HasForeignKey("MaNguyenLieu")
                        .IsRequired()
                        .HasConstraintName("FK__NguyenLie__MaNgu__123EB7A3");

                    b.HasOne("FAB.Server.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("NguyenLieuNccs")
                        .HasForeignKey("MaNhaCungCap")
                        .IsRequired()
                        .HasConstraintName("FK__NguyenLie__MaNha__1332DBDC");

                    b.Navigation("MaNguyenLieuNavigation");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.PhieuNhapKho", b =>
                {
                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiTaoNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaNguoiTao")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuNhap__MaNgu__71D1E811");

                    b.HasOne("FAB.Server.Models.NhaCungCap", "MaNhaCungCapNavigation")
                        .WithMany("PhieuNhapKhos")
                        .HasForeignKey("MaNhaCungCap")
                        .HasConstraintName("FK__PhieuNhap__MaNha__02FC7413");

                    b.Navigation("MaNguoiTaoNavigation");

                    b.Navigation("MaNhaCungCapNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.PhieuXuatKho", b =>
                {
                    b.HasOne("FAB.Server.Models.NguoiDung", "MaNguoiTaoNavigation")
                        .WithMany("PhieuXuatKhos")
                        .HasForeignKey("MaNguoiTao")
                        .IsRequired()
                        .HasConstraintName("FK__PhieuXuat__MaNgu__7A672E12");

                    b.Navigation("MaNguoiTaoNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.SanPham", b =>
                {
                    b.HasOne("FAB.Server.Models.DanhMuc", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham__MaDanhM__5165187F");

                    b.Navigation("MaDanhMucNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.SanPhamTopping", b =>
                {
                    b.HasOne("FAB.Server.Models.SanPham", "MaSanPhamNavigation")
                        .WithMany("SanPhamToppings")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__SanPham_T__MaSan__5DCAEF64");

                    b.HasOne("FAB.Server.Models.Topping", "MaToppingNavigation")
                        .WithMany("SanPhamToppings")
                        .HasForeignKey("MaTopping")
                        .IsRequired()
                        .HasConstraintName("FK__SanPham_T__MaTop__5EBF139D");

                    b.Navigation("MaSanPhamNavigation");

                    b.Navigation("MaToppingNavigation");
                });

            modelBuilder.Entity("FAB.Server.Models.ThanhToan", b =>
                {
                    b.HasOne("FAB.Server.Models.HoaDon", "MaHoaDonNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaHoaDon")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__MaHoa__3493CFA7");

                    b.Navigation("MaHoaDonNavigation");
                });

            modelBuilder.Entity("VaiTroQuyen", b =>
                {
                    b.HasOne("FAB.Server.Models.Quyen", null)
                        .WithMany()
                        .HasForeignKey("MaQuyen")
                        .IsRequired()
                        .HasConstraintName("FK__VaiTro_Qu__MaQuy__3D5E1FD2");

                    b.HasOne("FAB.Server.Models.VaiTro", null)
                        .WithMany()
                        .HasForeignKey("MaVaiTro")
                        .IsRequired()
                        .HasConstraintName("FK__VaiTro_Qu__MaVai__3C69FB99");
                });

            modelBuilder.Entity("FAB.Server.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("FAB.Server.Models.DonDatHangNhap", b =>
                {
                    b.Navigation("ChiTietDonDatHangNhaps");
                });

            modelBuilder.Entity("FAB.Server.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("GiaoHangs");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("FAB.Server.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("FAB.Server.Models.HoaDon", b =>
                {
                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("FAB.Server.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("FAB.Server.Models.MaGiamGia", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("FAB.Server.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGiaSanPhams");

                    b.Navigation("DonDatHangNhaps");

                    b.Navigation("DonHangs");

                    b.Navigation("GioHangs");

                    b.Navigation("KhachHangs");

                    b.Navigation("LichSuChatAis");

                    b.Navigation("LichSuTonKhos");

                    b.Navigation("PhieuNhapKhos");

                    b.Navigation("PhieuXuatKhos");
                });

            modelBuilder.Entity("FAB.Server.Models.NguyenLieu", b =>
                {
                    b.Navigation("AiduBaoTonKhos");

                    b.Navigation("ChiTietDonDatHangNhaps");

                    b.Navigation("ChiTietPhieuNhapKhos");

                    b.Navigation("ChiTietPhieuXuatKhos");

                    b.Navigation("CongThucSanPhams");

                    b.Navigation("LichSuTonKhos");

                    b.Navigation("NguyenLieuNccs");
                });

            modelBuilder.Entity("FAB.Server.Models.NhaCungCap", b =>
                {
                    b.Navigation("DonDatHangNhaps");

                    b.Navigation("NguyenLieuNccs");

                    b.Navigation("PhieuNhapKhos");
                });

            modelBuilder.Entity("FAB.Server.Models.PhieuNhapKho", b =>
                {
                    b.Navigation("ChiTietPhieuNhapKhos");
                });

            modelBuilder.Entity("FAB.Server.Models.PhieuXuatKho", b =>
                {
                    b.Navigation("ChiTietPhieuXuatKhos");
                });

            modelBuilder.Entity("FAB.Server.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("ComboChiTiets");

                    b.Navigation("ComboThanhPhanCua");

                    b.Navigation("CongThucSanPhams");

                    b.Navigation("DanhGiaSanPhams");

                    b.Navigation("HinhAnhSanPhams");

                    b.Navigation("SanPhamToppings");
                });

            modelBuilder.Entity("FAB.Server.Models.Topping", b =>
                {
                    b.Navigation("SanPhamToppings");
                });

            modelBuilder.Entity("FAB.Server.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
